language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"

install:
  # Log HTTP requests
  - npm config set loglevel http
  - gem install sass
  - time make

before_script:
  - mkdir -p $LOGS_DIR

script:
  - npm test

