language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"

install:
  # Log HTTP requests
  - npm config set loglevel http
  - gem install sass
  - time make

script:
  - npm test

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
